authapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
   path('login/', authapp.UserLoginView.as_view(), name='login'),
   path('register/', authapp.UserCreateView.as_view(), name='register'),
   path('logout/', authapp.UserLogoutView.as_view(), name='logout'),
   path('profile/', login_required(authapp.UserUpdateView.as_view()), name='profile'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
   path('basket-add/<int:product_id>/', basketapp.basket_add, name='basket_add'),
   path('basket-delete/<int:id>/', basketapp.basket_delete, name='basket_delete'),
   path('basket-edit/<int:id>/<int:quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket-elements/', include('basketapp.urls', namespace='basket_elements')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from authapp.models import User
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Корзина для {self.user.username} | Продукт {self.product.name}"

    @property
    def sum(self):
        return self.quantity * self.product.price

    def total_sum(self):
        return sum([elem.quantity * elem.product.price for elem in
                    Basket.objects.filter(user=self.user)]) if Basket.objects.filter(user=self.user) else 0

    def total_count(self):
        return sum([elem.quantity for elem in Basket.objects.filter(user=self.user)]) if Basket.objects.filter(
            user=self.user) else 0

basketapp/views.py
from django.shortcuts import HttpResponseRedirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from mainapp.models import Product
from basketapp.models import Basket


@login_required
def basket_add(request, product_id=None):
    product = Product.objects.get(id=product_id)
    basket_elements = Basket.objects.filter(user=request.user, product=product)

    if not basket_elements.exists():
        basket = Basket(user=request.user, product=product)
        basket.quantity = 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = basket_elements.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, id=None):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()

        context = {'basket': Basket.objects.filter(user=request.user)}
        result = render_to_string('basketapp/basket.html', context)
        return JsonResponse({'result': result})

basketapp/templates/basketapp/basket.html
{% load additional_formating %}
<div class="basket-list">
    {% if basket %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ basket.0.total_count }}</span>
        </h4>
        {% for elem in basket %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ elem.product.name }}</h5>
                    <p class="card-text">{{ elem.product.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ elem.id }}" type="number" class="form-control"
                                       value="{{ elem.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ elem.sum|pricing }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'basket_elements:basket_delete' elem.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ basket.0.total_sum|pricing }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% else %}
        <h4 class="mt-3 mb-3 text-center">
            Корзина пуста
        </h4>
    {% endif %}
</div>