authapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
   path('login/', authapp.UserLoginView.as_view(), name='login'),
   path('register/', authapp.UserCreateView.as_view(), name='register'),
   path('logout/', authapp.UserLogoutView.as_view(), name='logout'),
   path('profile/', login_required(authapp.UserUpdateView.as_view()), name='profile'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
   path('basket-add/<int:product_id>/', basketapp.basket_add, name='basket_add'),
   path('basket-delete/<int:id>/', basketapp.basket_delete, name='basket_delete'),
   path('basket-edit/<int:id>/<int:quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket-elements/', include('basketapp.urls', namespace='basket_elements')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.ProductsView.as_view(), name='index'),
   re_path(r'(?:category-(?P<cat_key>\d+)/)?(?:(?P<page>\d+)/)?$', mainapp.ProductsView.as_view(), name='products'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    categories = models.ManyToManyField(ProductCategory)

    def __str__(self):
        return self.name

mainapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic.list import ListView

from mainapp.models import Product, ProductCategory


def index(request):
    context = {'title': 'GeekShop'}
    return render(request, 'mainapp/index.html', context)


class ProductsView(ListView):
    model = Product
    template_name = 'mainapp/products.html'

    def __init__(self):
        super(ProductsView, self).__init__()
        self.page = 1
        self.cat_key = None

    def get_queryset(self):
        queryset = super(ProductsView, self).get_queryset()
        if self.kwargs.get('cat_key'):
            self.queryset = queryset.filter(categories=self.kwargs.get('cat_key'))
            self.cat_key = self.kwargs.get('cat_key')
        else:
            self.queryset = queryset.all()
        if self.kwargs.get('page'):
            self.page = self.kwargs.get('page')
        else:
            self.page = 1

    def get_context_data(self, **kwargs):
        kwargs = super(ProductsView, self).get_context_data(**kwargs)
        kwargs.update({
            'title': 'GeekShop - Каталог',
            'categories': ProductCategory.objects.all(),
            'cur_cat': self.cat_key,
        })
        paginator = Paginator(self.queryset, per_page=3)
        products_paginator = paginator.page(self.page)
        kwargs.update({'products': products_paginator})

        return kwargs

mainapp/templates/mainapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% if request.path != '/products/' %}{% url 'products:index' %}{% else %}#{% endif %}">Каталог
                        <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_staff:index' %}">Панель админимстратора
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:profile' %}">{{ user }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/basket.js' %}"></script>

</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load additional_formating %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:products' cat_key=category.id page=1 %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="/media/{{ product.image }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price|pricing }} руб.</h5>
                                    <p class="card-text">{{ product.short_description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'basket_elements:basket_add' product.id %}">
                                        <button type="button"
                                                class="btn btn-outline-success">Отправить в корзину
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item{% if not products.has_previous %} disabled{% endif %}">
                            <a class="page-link"
                               {% if cur_cat %}
                                    href="{% if products.has_previous %}{% url 'products:products' cat_key=cur_cat page=products.previous_page_number %}{% else %}#{% endif %}"
                               {% else %}
                                    href="{% if products.has_previous %}{% url 'products:products' page=products.previous_page_number %}{% else %}#{% endif %}"
                               {% endif %}
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item{% ifequal page products.number %} disabled{% endifequal %}">
                            <a class="page-link"
                                {% if cur_cat %}
                                    href="{% url 'products:products' cat_key=cur_cat page=page %}"
                                {% else %}
                                    href="{% url 'products:products' page=page %}"
                                {% endif %}
                                >{{ page }}</a>
                            </li>
                        {% endfor %}
                        <li class="page-item{% if not products.has_next %} disabled{% endif %}">
                            <a class="page-link"
                                {% if cur_cat %}
                                    href="{% if products.has_next %}{% url 'products:products' cat_key=cur_cat page=products.next_page_number %}{% else %}#{% endif %}">Next</a>
                                {% else %}
                                    href="{% if products.has_next %}{% url 'products:products' page=products.next_page_number %}{% else %}#{% endif %}">Next</a>
                                {% endif %}
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop {% now 'Y' %}</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}